set -x
db_path="/storage/testdb"
dataset=$((100 * 1024 * 1024 * 1024))
vsize=4096
ksize=24
num_threads=32

num_keys=$((dataset / (ksize + vsize)))
num_writes=$((num_keys / num_threads))

echo "dataset size:       $((dataset / 1024 / 1024 / 1024)) GB"
echo "key size:           $ksize"
echo "average value size: $vsize"
echo "number of keys:     $num_keys"

# 1 bulkload 85% without compaction
./build/db_bench --benchmarks=fillseq --use_existing_db=false --num=$num_keys --key_size=$ksize --value_size=$vsize --threads=1 --disable_auto_compactions=false --disable_wal=true --sync=0 --db=$db_path --db_log_dir=./log_rocksdb --wal_dir=${db_path}/benchdb_lava_nonsep --num_levels=5 --block_size=16384 --cache_numshardbits=10 --compression_max_dict_bytes=0 --compression_ratio=0.5 --compression_type=none --level_compaction_dynamic_level_bytes=true --cache_index_and_filter_blocks=false --pin_l0_filter_and_index_blocks_in_cache=false --benchmark_write_rate_limit=$((100<<30)) --benchmark_read_rate_limit=$((1<<30)) --write_buffer_size=67108864 --target_file_size_base=67108864 --verify_checksum=1 --max_bytes_for_level_multiplier=10 --statistics=1 --stats_interval_seconds=60 --histogram=1 --memtablerep=skip_list --bloom_bits=10 --open_files=-1 --duration=0 --level0_file_num_compaction_trigger=4 --level0_slowdown_writes_trigger=21 --level0_stop_writes_trigger=36 --max_background_compactions=14 --max_background_flushes=2 --max_background_garbage_collections=4 --max_write_buffer_number=4 --mmap_read=false --delayed_write_rate=8388608 --max_total_wal_size=1073741824 --subcompactions=1 --compaction_readahead_size=$((2<<20)) --table_cache_numshardbits=6 --dump_malloc_stats=false --stats_dump_period_sec=300 --use_direct_reads=true --wal_bytes_per_sync=0 --perf_level=2 --soft_pending_compaction_bytes_limit=$((64<<30)) --hard_pending_compaction_bytes_limit=$((128<<30)) --max_compaction_bytes=$((2<<30)) --max_bytes_for_level_base=$((256<<20)) --pin_top_level_index_and_filter=false --batch_size=1 --compaction_pri=3 --seed=1762163642 --blob_size=512 --blob_gc_ratio=0.2 --target_blob_file_size=$((512<<20)) --blob_file_defragment_size=$((32<<20)) --cache_size=$((1<<30)) 2>&1 | tee log_rocksdb/bulkload.txt

# 2 load 15% with compaction
./build/db_bench --benchmarks=compact --use_existing_db=true --num=$num_keys --key_size=$ksize --value_size=$vsize --threads=1 --disable_auto_compactions=false --disable_wal=true --sync=0 --db=$db_path --db_log_dir=./log_rocksdb --wal_dir=${db_path}/benchdb_lava_nonsep --num_levels=5 --block_size=16384 --cache_numshardbits=10 --compression_max_dict_bytes=0 --compression_ratio=0.5 --compression_type=none --level_compaction_dynamic_level_bytes=true --cache_index_and_filter_blocks=false --pin_l0_filter_and_index_blocks_in_cache=false --benchmark_write_rate_limit=$((100<<30)) --benchmark_read_rate_limit=$((1<<30)) --write_buffer_size=67108864 --target_file_size_base=67108864 --verify_checksum=1 --max_bytes_for_level_multiplier=10 --statistics=1 --stats_interval_seconds=60 --histogram=1 --memtablerep=skip_list --bloom_bits=10 --open_files=-1 --duration=900 --level0_file_num_compaction_trigger=4 --level0_slowdown_writes_trigger=21 --level0_stop_writes_trigger=36 --max_background_compactions=14 --max_background_flushes=2 --max_background_garbage_collections=4 --max_write_buffer_number=4 --mmap_read=false --delayed_write_rate=8388608 --max_total_wal_size=1073741824 --subcompactions=1 --compaction_readahead_size=$((2<<20)) --table_cache_numshardbits=6 --dump_malloc_stats=false --stats_dump_period_sec=300 --use_direct_reads=true --wal_bytes_per_sync=0 --perf_level=2 --soft_pending_compaction_bytes_limit=$((64<<30)) --hard_pending_compaction_bytes_limit=$((128<<30)) --max_compaction_bytes=$((2<<30)) --max_bytes_for_level_base=$((256<<20)) --pin_top_level_index_and_filter=false --batch_size=1 --compaction_pri=3 --seed=1762163642 --blob_size=512 --blob_gc_ratio=0.2 --target_blob_file_size=$((512<<20)) --blob_file_defragment_size=$((32<<20)) --cache_size=$((1<<30)) 2>&1 | tee log_rocksdb/compact.txt

# 3 update 150%
./build/db_bench --benchmarks=overwrite --use_existing_db=true --num=$((num_keys * 15 / 10)) --key_size=$ksize --value_size=$vsize --threads=$num_threads --disable_auto_compactions=false --disable_wal=true --sync=0 --db=$db_path --db_log_dir=./log_rocksdb --wal_dir=${db_path}/benchdb_lava_nonsep --num_levels=5 --block_size=16384 --cache_numshardbits=10 --compression_max_dict_bytes=0 --compression_ratio=0.5 --compression_type=none --level_compaction_dynamic_level_bytes=true --cache_index_and_filter_blocks=false --pin_l0_filter_and_index_blocks_in_cache=false --benchmark_write_rate_limit=$((100<<30)) --benchmark_read_rate_limit=$((1<<30)) --write_buffer_size=67108864 --target_file_size_base=67108864 --verify_checksum=1 --max_bytes_for_level_multiplier=10 --statistics=1 --stats_interval_seconds=60 --histogram=1 --memtablerep=skip_list --bloom_bits=10 --open_files=-1 --duration=3600 --level0_file_num_compaction_trigger=4 --level0_slowdown_writes_trigger=21 --level0_stop_writes_trigger=36 --max_background_compactions=14 --max_background_flushes=2 --max_background_garbage_collections=4 --max_write_buffer_number=4 --mmap_read=false --delayed_write_rate=8388608 --max_total_wal_size=1073741824 --subcompactions=1 --compaction_readahead_size=$((2<<20)) --table_cache_numshardbits=6 --dump_malloc_stats=false --stats_dump_period_sec=300 --use_direct_reads=true --wal_bytes_per_sync=0 --perf_level=2 --soft_pending_compaction_bytes_limit=$((64<<30)) --hard_pending_compaction_bytes_limit=$((128<<30)) --max_compaction_bytes=$((2<<30)) --max_bytes_for_level_base=$((256<<20)) --pin_top_level_index_and_filter=false --batch_size=1 --compaction_pri=3 --seed=1762163642 --blob_size=512 --blob_gc_ratio=0.2 --target_blob_file_size=$((512<<20)) --blob_file_defragment_size=$((32<<20)) --cache_size=$((1<<30)) 2>&1 | tee log_rocksdb/overwrite.txt

exit 0